import Head from "next/head";
import Link from "next/link";
import ProjectCard from "@/components/ProjectCard";
import {
  AiFillGithub,
  AiFillMail
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";

export default function Home({ data }) {
    const [darkMode, setDarkMode] = useState(false);
  
    return (
      <div className={darkMode ? "dark" : ""}>
        <Head>
          <title>Cameron Philbert</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
          <section>
            <nav className="py-10 mb-12 flex justify-between dark:text-white">
              <h1 className="font-burtons text-xl">developedbycam</h1>
              <ul className="flex items-center">
                <Link href="/">Home</Link>
                <Link href="/projects" className="px-10">Projects</Link>
                <li>
                  <BsFillMoonStarsFill
                    onClick={() => setDarkMode(!darkMode)}
                    className=" cursor-pointer text-2xl"
                  />
                </li>
                <li>
                  <a
                    className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                    href="#">
                    Resume
                  </a>
                </li>
              </ul>
            </nav>
          </section>

          <section className="py-10">
            <div>
                <h2 className="text-5xl">Projects</h2>
            </div>
            <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
                {data.data.map((project) => (
                    <ProjectCard key={project.id} project={project} />
                ))}
            </div>
          </section>
        </main>
      </div>
    );
  }
  
  export async function getServerSideProps() {
    // Replace this URL with the API endpoint you want to fetch data from.
    const apiUrl = 'http://localhost:3000/projects';
  
    const res = await fetch(apiUrl);
    const data = await res.json();
  
    // If there's an error or the data is empty, return an empty array.
    if (!data || data.error) {
      return { props: { data: [] } };
    }
  
    //console.log(data.data)
    return { props: { data } };
  }


